/* DO NOT EDIT THIS FILE - it is machine generated */
//#include "../../../../../../../../Android/dev_tool/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/jni.h"
///* Header for class com_yasin_explore_Jni */
//
//#ifndef _Included_com_yasin_explore_Jni
//#define _Included_com_yasin_explore_Jni
//#ifdef __cplusplus
//extern "C" {
//#endif
///*
// * Class:     com_yasin_explore_Jni
// * Method:    getString
// * Signature: ()Ljava/lang/String;
// */
//JNIEXPORT jstring JNICALL Java_com_yasin_explore_Jni_getString(JNIEnv *, jobject clazz);
//
//#ifdef __cplusplus
//}
//#endif
//#endif
